---
roles:
  - src: git+https://gitlab.com/Orange-OpenSource/lfn/infra/create_disk_role.git
    version: master
    name: create_disk
  - src: git+https://gitlab.com/Orange-OpenSource/lfn/infra/apt-install-role.git
    version: master
    name: apt_install
collections:
  - name: ansible.netcommon
    source: https://galaxy.ansible.com
    version: 2.5.1
  - name: community.kubernetes
    source: https://galaxy.ansible.com
    version: 1.1.1
  - name: openstack.cloud
    source: https://galaxy.ansible.com
    version: 1.1.0
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 1.1.1
  - name: community.general
    source: https://galaxy.ansible.com
    version: 1.2.0
  - name: https://gitlab.com/Orange-OpenSource/lfn/infra/os_infra_manager_collection.git
    type: git
    version: staging
